package com.github.shiayanga.xinchaung.dameng.entity;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITY.CITY_ID
     *
     * @mbg.generated Fri Jul 21 19:06:17 CST 2023
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITY.CITY_NAME
     *
     * @mbg.generated Fri Jul 21 19:06:17 CST 2023
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITY.REGION_ID
     *
     * @mbg.generated Fri Jul 21 19:06:17 CST 2023
     */
    private Integer regionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITY.CITY_ID
     *
     * @return the value of CITY.CITY_ID
     *
     * @mbg.generated Fri Jul 21 19:06:17 CST 2023
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITY.CITY_ID
     *
     * @param cityId the value for CITY.CITY_ID
     *
     * @mbg.generated Fri Jul 21 19:06:17 CST 2023
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITY.CITY_NAME
     *
     * @return the value of CITY.CITY_NAME
     *
     * @mbg.generated Fri Jul 21 19:06:17 CST 2023
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITY.CITY_NAME
     *
     * @param cityName the value for CITY.CITY_NAME
     *
     * @mbg.generated Fri Jul 21 19:06:17 CST 2023
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITY.REGION_ID
     *
     * @return the value of CITY.REGION_ID
     *
     * @mbg.generated Fri Jul 21 19:06:17 CST 2023
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITY.REGION_ID
     *
     * @param regionId the value for CITY.REGION_ID
     *
     * @mbg.generated Fri Jul 21 19:06:17 CST 2023
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }
}