---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LiYang.
--- DateTime: 2023/1/3 16:30
---

-- print("Lua <<<<<<<<<<<<>>>>>>>>>> Hello World!")

a = 0;
for i = 0, 100000, 1 do
    a = a + i;
end

-- print(a)