spring:
  datasource:
    password: SYSDBA
    username: SYSDBA
    url: jdbc:dm://localhost:5236?scheme=DMHR
    driver-class-name: dm.jdbc.driver.DmDriver
server:
  port: 9909

logging:
  level:
    root: debug

mybatis:
  mapper-locations: classpath:**/mapper/*.xml